// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	DeleteAcc(ctx context.Context, id int64) error
	GetAcc(ctx context.Context, id int64) (Account, error)
	GetAccForUpdate(ctx context.Context, id int64) (Account, error)
	GetAllAccs(ctx context.Context) ([]Account, error)
	GetAllEntries(ctx context.Context, accID sql.NullInt64) ([]Entry, error)
	GetAllTransfers(ctx context.Context, arg GetAllTransfersParams) ([]Transfer, error)
	GetEntry(ctx context.Context, id int64) (Entry, error)
	GetTransfer(ctx context.Context, id int64) (Transfer, error)
	NewAcc(ctx context.Context, arg NewAccParams) (Account, error)
	NewEntry(ctx context.Context, arg NewEntryParams) (Entry, error)
	NewTransfer(ctx context.Context, arg NewTransferParams) (Transfer, error)
	UpdateAcc(ctx context.Context, arg UpdateAccParams) (Account, error)
	UpdateAccBalance(ctx context.Context, arg UpdateAccBalanceParams) (Account, error)
}

var _ Querier = (*Queries)(nil)
